CREATE DOMAIN D_HTTP_METHOD
AS VARCHAR(6)
CHECK (VALUE IN ('GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE'));

SET TERM ^ ;

CREATE OR ALTER PACKAGE HTTP_UTILS
AS
BEGIN
  PROCEDURE SEND_REQUEST (
    METHOD               D_HTTP_METHOD NOT NULL,
    URL                  VARCHAR(1024) NOT NULL,
    REQUEST_BODY         BLOB SUB_TYPE TEXT DEFAULT NULL,
    REQUEST_TYPE         VARCHAR(256) DEFAULT NULL,
    HEADERS              VARCHAR(8191) DEFAULT NULL
  )
  RETURNS (
    STATUS_CODE          SMALLINT,
    STATUS_TEXT          VARCHAR(256),
    RESPONSE_TYPE        VARCHAR(256),
    RESPONSE_BODY        BLOB SUB_TYPE TEXT,
    RESPONSE_HEADERS     BLOB SUB_TYPE TEXT
  );

  FUNCTION URL_ENCODE (
    URL VARCHAR(1024)
  )
  RETURNS VARCHAR(1024);

  FUNCTION URL_DECODE (
    URL VARCHAR(1024)
  )
  RETURNS VARCHAR(1024);
END^

RECREATE PACKAGE BODY HTTP_UTILS
AS
BEGIN
  PROCEDURE SEND_REQUEST (
    METHOD               D_HTTP_METHOD NOT NULL,
    URL                  VARCHAR(1024) NOT NULL,
    REQUEST_BODY         BLOB SUB_TYPE TEXT,
    REQUEST_TYPE         VARCHAR(256),
    HEADERS              VARCHAR(8191)
  )
  RETURNS (
    STATUS_CODE          SMALLINT,
    STATUS_TEXT          VARCHAR(256),
    RESPONSE_TYPE        VARCHAR(256),
    RESPONSE_BODY        BLOB SUB_TYPE TEXT,
    RESPONSE_HEADERS     BLOB SUB_TYPE TEXT
  )
  EXTERNAL NAME 'http_client_udr!sendHttpRequest'
  ENGINE UDR;

  FUNCTION URL_ENCODE (
    URL VARCHAR(1024)
  )
  RETURNS VARCHAR(1024)
  EXTERNAL NAME 'http_client_udr!urlEncode'
  ENGINE UDR;

  FUNCTION URL_DECODE (
    URL VARCHAR(1024)
  )
  RETURNS VARCHAR(1024)
  EXTERNAL NAME 'http_client_udr!urlDecode'
  ENGINE UDR;
END
^

SET TERM ; ^
